### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by apoorvapendse** [arya2004/AutoExpress#2]
![Screenshot from 2023-09-02 08-49-28](https://github.com/arya2004/AutoExpress/assets/102853901/c404220c-6c85-46ed-b911-4ee52caa69bf)

![image](https://github.com/arya2004/AutoExpress/assets/102853901/ce45c58f-2fe2-42b4-93aa-a0a88ab167b2)

**Comment by arya2004** [comment]
- My apologies, but this was only supposed to work on windows 10

**Comment by apoorvapendse** [comment]
![image](https://github.com/arya2004/AutoExpress/assets/102853901/c805b125-99cf-41c7-b99e-898d10dc74f3)

linux fix

**Comment by apoorvapendse** [comment]
https://stackoverflow.com/a/13702462/21940401
